crmdjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customersite/',include('customersite.urls')),
    
    
    
    
    
    
    
]

customersite/urls.py
app_name='customersite'
from django.urls import path
from . import views

from django.views.generic.base import TemplateView


urlpatterns=[
   path('',TemplateView.as_view(template_name='customersite/home.html'),name='home'),
   path('homepage',TemplateView.as_view(template_name='customersite/index.html'),name='index'),
   path('login',TemplateView.as_view(template_name='customersite/login.html'),name='login'),
   path('login/',views.login_user,name='login_user'),
   path('logout/',views.logout_user,name='logout'),
   path('register/',views.register_user,name='register'),
   path('record',views.EnterView.as_view(),name='enter'),
   path('records/<int:pk>/',views.customer_record,name='detail'),
   path('record_delete/<int:pk>/',views.delete_record,name='delete'),
   path('record/<int:pk>/update',views.update_record,name='update'),
   path('record/add',views.add_record,name='addrecord'),
  
    
    
    
    
]

customersite/models.py
from django.db import models

# Create your models here.
class Record(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    email=models.CharField(max_length=100)
    phone=models.CharField(max_length=100)
    address=models.CharField(max_length=50)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    zipcode=models.CharField(max_length=20)
    def __str__(self):
        return(f"{self.first_name}  {self.last_name}")
    

customersite/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record



class SignUpForm(UserCreationForm):
    email=forms.EmailField(label="",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email Address'}))
    first_name=forms.CharField(label="",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name '}))
    last_name=forms.CharField(label="",widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Lastname'}))
    
    class Meta:
        model=User
        fields=('username','first_name','last_name','email','password1','password2')

    def __init__(self,*args,**kwargs):
        super(SignUpForm,self).__init__(*args,**kwargs)
        
        self.fields['username'].widget.attrs['class']='form-control'
        self.fields['username'].widget.attrs['placeholder']='Enter Username'
        self.fields['username'].widget.label=''
        self.fields['username'].help_text='<span class="form-text text-muted small"> Your Username should only have letters </span>'
            
        self.fields['password1'].widget.attrs['class']='form-control'
        self.fields['password1'].widget.attrs['placeholder']='Enter password'
        self.fields['password1'].widget.label=''
        self.fields['password1'].help_text='<span class="form-text text-muted small"> <ul> <li> Your password can\'t be too similar </li><li> Password should be nice and contain letters, numbers all mixed</li><li> It should be at least 8 letters long </li></ul></span>'
        
        self.fields['password2'].widget.attrs['class']='form-control'
        self.fields['password2'].widget.attrs['placeholder']='Confirm password again '
        self.fields['password2'].widget.label=''
        self.fields['password2'].help_text='<span class="form-text text-muted small"> Your Password</span>'
            
   
   
class AddRecordForm(forms.ModelForm):
    first_name=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter First name','class':'form-control'}))
    last_name=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter Last name','class':'form-control'}))
    email=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter Email Address','class':'form-control'}))
    phone=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter Phone Number','class':'form-control'}))
    address=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter your Address','class':'form-control'}))
    city=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter your City','class':'form-control'}))
    state=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter your State ','class':'form-control'}))
    zip_code=forms.CharField(required=True,widget=forms.widgets.TextInput(attrs={'placeholder':'Enter Zip Code ','class':'form-control'}))
   
   
   
    class Meta:
        model=Record
        fields=('__all__')
        #exclude = ("user",)
        

customersite/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView




# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .forms import SignUpForm, AddRecordForm
from .models import Record

class EnterView(ListView):
    model=Record
    template_name='customersite/index.html'

def login_user(request):
    #Check to see if loggin in 
    #records=Record.objects.all()

    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        #Authenticate 
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,"You have been logged in ")
            return redirect('customersite:enter')
            #return render(request,'customersite/index.html',{'records':records})
            
        else:
            messages.success(request,"Sorry, there was an error, try again !!!")
            return redirect('customersite:home')
    else:
        return render(request,'customersite/index.html',{
       # 'records':records # We show the records, since the user must be in already 
        })
        
        


def logout_user(request):
    logout(request)
    messages.success(request,"You have been logged out")
    return redirect("customersite:home")

def register_user(request):
    if request.method=="POST":
        form=SignUpForm(request.POST)  #Send the post details to our signup form
        if form.is_valid():
            form.save()
            #Authenticate and log then in 
            username=form.cleaned_data['username']  #Th form.cleaned_data essentially allows to pull the username entry
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            messages.success(request,"You have been sucessfully registered")
            return redirect('customersite:home')
            
    else:
        form=SignUpForm() #Here we are not passing the request, since they are not filled yet 
        return render(request,'customersite/register.html',{'form':form})
    return render(request,'customersite/register.html',{'form':form}) #In case there is an error, this returns 
        


def customer_record(request,pk):
    if request.user.is_authenticated:
        customer_records=Record.objects.get(id=pk)
        return render(request,'customersite/detail.html',{'detail':customer_records})
    
    else:
        messages.success(request,"You must be logged in")
        return redirect('customersite:home')
    
def delete_record(request,pk):
    if request.user.is_authenticated:
        delete_it=Record.objects.get(id=pk)
        delete_it.delete()
        messages.success(request,"Deleted Successfully")
        return redirect('customersite:enter')
        
    else:
        messages.success(request,"You must be logged in")
        return redirect('customersite:home')
        
        
def update_record(request,pk):
    if request.user.is_authenticated:
        current_record=Record.objects.get(id=pk)
        form=AddRecordForm(request.POST or None, instance=current_record)
        if form.is_valid():
            form.save()
            messages.success(request,'Records updated succesfully...')
            return redirect('customersite:enter')

        return render(request,'customersite/updaterecord.html',{'form':form})      
    else:
        messages.success(request,'You must be logged in ...')
        return redirect('customersite:home')  
        





def add_record(request):
    form=AddRecordForm(request.POST or None)
    if request.user.is_authenticated:
        if request.method=="POST":
            if form.is_valid():
                add_record=form.save()  #We don't need to call the model h=again sunce, its been inherited by the form itself in forms.py
                messages.success(request,"Record added successfully ...")
                return redirect('customersite:enter')
        return render(request,'customersite/addrecord.html',{'form':form})
    else:
        messages.success(request,'You must be logged in')
        return redirect('customersite:home')

   
        

templates/customersite/addrecord.html
{% extends 'customersite/base.html' %}



{% block content %}

<h2> Add Record here </h2>

<div class="col-md-6 offset-3">
<form method="POST">

   {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary"> Add Record </button>
</form>
</div>
    
{% endblock content %}
    

templates/customersite/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/customersite/main.css' %}" >
    <title>Customer Relational Manager </title>
  </head>
  <body>
    {% include 'customersite/navbar.html' %}
   
   
    {% block content %}
    
    <div class="container">

      <!----- Space for Navbar -->
    
     
      
     
    </div>

      
    {% endblock content %}
    
    



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/customersite/detail.html
{% extends 'customersite/base.html' %}



{% block content %}

{% if detail %}

<div class="responsive">
<table class="table"> 
    <caption> Records of {{ detail.first_name }} {{ detail.last_name }} </caption>
    <thead>
    <tr>
          
               <th scope="col"> First Name </th>
               <th scope="col"> Last Name </th>
               <th scope="col"> Email </th>
               <th scope="col"> Address </th>
               <th scope="col"> State </th>
               <th scope="col"> City </th>
               <th scope="col"> Zip code </th>
               <th scope="col"> Date Created </th>
               <th scope="col"> ID </th>
               <th scope="col"> Delete </td>
    </tr>
</thead>
    

  
    <tbody>
       

            <tr scope="row">
                <td> {{ detail.first_name }} </td>
                <td> {{ detail.last_name }} </td>
                <td>{{ detail.email }} </td>
                <td> {{ detail.address }} </td>
                <td> {{ detail.state }} </td>
                <td>{{ detail.city }}</td>
                <td>{{ detail.zip_code }}</td>
                <td> {{ detail.created_at }} </td>
                <td>  {{ detail.id}} </td>
                <td> <a href="{% url 'customersite:delete' detail.id %}" class="btn btn-secondary">Delete</a></td>

                
            </tr>
            
       
        </tbody>

      
        

      </table>
    </div>
      <a href="{% url 'customersite:enter'%}" class="btn btn-secondary">Back </a>
    <a href="{% url 'customersite:update' detail.id %}" class="btn btn-primary"> Edit Record </a>

    {% endif %}
     

    
{% endblock content %}
    

templates/customersite/home.html
{% extends 'customersite/base.html' %}



{% block content %}

<h2> Here is the Home Page of Customer Relation Manager Site </h2> 
<p> Please click on the links above to navigate your ways properly </p>


{% endblock content %}

templates/customersite/index.html
{% extends 'customersite/base.html' %}
{% load static %}


{% block content %}

    {% if user.is_authenticated %}

        <h1> Welcome    {{ user.username }} </h1>

            {% if object_list %}

            
            <table class="table"> <!-- Please use Bootstrap 4 table to style this later with borders, responsive etc -->
                
                <thead>
                <tr>
                      
                           <th scope="col"> First Name </th>
                           <th scope="col"> Last Name </th>
                           <th scope="col"> Email </th>
                           <th scope="col"> Address </th>
                           <th scope="col"> State </th>
                           <th scope="col"> City </th>
                           <th scope="col"> Zip code </th>
                           <th scope="col"> Date Created </th>
                           <th scope="col"> ID </th>
                           <th scope="col"> Delete </th>
                </tr>
            </thead>
                
                 
            {% for record in object_list %} <!-- You can use Bootstrap cards here -->   
                <tbody>

                        <tr scope="row">

                            <td> {{ record.first_name }} </td>
                            <td> {{ record.last_name }} </td>
                            <td>{{ record.email }} </td>
                            <td> {{ record.address }} </td>
                            <td> {{ record.state }} </td>
                            <td>{{ record.city }}</td>
                            <td>{{ record.zip_code }}</td>
                            <td> {{ record.created_at }} </td>
                            <td>  <a href="{% url 'customersite:detail' record.id %}"> {{ record.id}} </a></td>
                            <td> <a href="{% url 'customersite:delete' record.id %}" class="btn btn-secondary">Delete</a></td>
                      
                        </tr>
                    </tbody>
                      
                    {% endfor %}

                  
                    

                  </table>
               
            {% endif %}

    {% endif %}

    
{% endblock content %}
    

templates/customersite/login.html
{% extends 'customersite/base.html' %}

{% block content %}


<div class="col-md-6 offset-md-3">
    <h3> Login </h3>

    <form method="POST" action="{% url 'customersite:login_user' %}">
        
        {% csrf_token %}
       <div class="mb-3">
        <input type="text" class="form-control" name="username" placeholder="Enter Name" required>
       </div>
       <div class="mb-3">
        <input type="password" class="form-control" name="password" placeholder="Enter Password" required>
       </div>
       
        
        <button type="submit" class="btn btn-secondary"> Login </button>


    </form>

</div>



{% endblock content %}

templates/customersite/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark custom-navbar" >
    <a class="navbar-brand text-white" href="#">Customer Relational Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {#  #}
       
       
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link text-white" href="#"> Welcome  <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'customersite:addrecord' %}">Add Record</a>
        </li>
        


        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'customersite:logout' %}">Logout</a>
        </li>


        

        {% else %}
        <li class="nav-item active">
          <a class="nav-link text-white" href="#"> You should log in <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'customersite:register'%}">Register </a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'customersite:login' %}">Login </a>
        </li>
        {% endif %}




       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled text-white" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

templates/customersite/register.html
{% extends 'customersite/base.html' %}



{% block content %}

<div class="col-md-6 offset-md-3">
    <h1> Register </h1>
    <br>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Ooops!!! Just  some errors </strong> <br>
        Guy
        {% for field in form %}
        {% if fields.errors %}
        {{ field.errors }}
        {% endif %}

        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>


<form method="POST" action="{% url 'customersite:register'%}">
       
{% csrf_token %}


{% comment %}
    We simply grab the forms that has been erstwhile preconfigured 


{% endcomment %}

{{ form.as_p }}
<button type="submit" class="btn btn-secondary"> Register </button>
    

    </form>

</div>
    
{% endblock content %}

    

templates/customersite/updaterecord.html
{% extends 'customersite/base.html' %}



{% block content %}

<div class="col-md-6 offset-3">
    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-secondary"> Update Record </button>
    </form>
</div>
    
{% endblock content %}


    